import { CategoryFilter } from '../../app/core/models/category.model';

export const categoryFilters: CategoryFilter[] = [
  {
    id: 'knives',
    placeholder: 'Cuchillos',
    selectedValue: '',
    options: [
      { value: 'knife', label: 'Todos los Cuchillos' },
      { value: 'bayonet', label: 'Bayonet' },
      { value: 'bowie', label: 'Bowie Knife' },
      { value: 'butterfly', label: 'Butterfly Knife' },
      { value: 'falchion', label: 'Falchion Knife' },
      { value: 'flip', label: 'Flip Knife' },
      { value: 'gut', label: 'Gut Knife' },
      { value: 'huntsman', label: 'Huntsman Knife' },
      { value: 'karambit', label: 'Karambit' },
      { value: 'm9-bayonet', label: 'M9 Bayonet' },
      { value: 'navaja', label: 'Navaja Knife' },
      { value: 'nomad', label: 'Nomad Knife' },
      { value: 'paracord', label: 'Paracord Knife' },
      { value: 'shadow daggers', label: 'Shadow Daggers' },
      { value: 'skeleton', label: 'Skeleton Knife' },
      { value: 'stiletto', label: 'Stiletto Knife' },
      { value: 'survival', label: 'Survival Knife' },
      { value: 'talon', label: 'Talon Knife' },
      { value: 'ursus', label: 'Ursus Knife' },
    ],
  },
  {
    id: 'gloves',
    placeholder: 'Guantes',
    selectedValue: '',
    options: [
      { value: 'glove', label: 'Todos los Guantes' },
      { value: 'driver', label: 'Driver Gloves' },
      { value: 'hand', label: 'Hand Wraps' },
      { value: 'moto', label: 'Moto Gloves' },
      { value: 'sport', label: 'Sport Gloves' },
      { value: 'specialist', label: 'Specialist Gloves' },
      { value: 'broken', label: 'Broken Fang Gloves' },
      { value: 'hydra', label: 'Hydra Gloves' },
    ],
  },
  {
    id: 'rifles',
    placeholder: 'Rifles',
    selectedValue: '',
    options: [
      { value: 'rifle', label: 'Todos los Rifles' },
      { value: 'ak-47', label: 'AK-47' },
      { value: 'm4a4', label: 'M4A4' },
      { value: 'm4a1-s', label: 'M4A1-S' },
      { value: 'aug', label: 'AUG' },
      { value: 'famas', label: 'FAMAS' },
      { value: 'galil', label: 'Galil AR' },
      { value: 'sg553', label: 'SG 553' },
    ],
  },
  {
    id: 'snipers',
    placeholder: 'Francotiradores',
    selectedValue: '',
    options: [
      { value: 'sniper', label: 'Todos los Francotiradores' },
      { value: 'awp', label: 'AWP' },
      { value: 'ssg08', label: 'SSG 08' },
      { value: 'g3sg1', label: 'G3SG1' },
      { value: 'scar-20', label: 'SCAR-20' },
    ],
  },
  {
    id: 'pistols',
    placeholder: 'Pistolas',
    selectedValue: '',
    options: [
      { value: 'pistol', label: 'Todas las Pistolas' },
      { value: 'glock-18', label: 'Glock-18' },
      { value: 'usp-s', label: 'USP-S' },
      { value: 'p250', label: 'P250' },
      { value: 'desert-eagle', label: 'Desert Eagle' },
      { value: 'five-seven', label: 'Five-SeveN' },
      { value: 'tec-9', label: 'Tec-9' },
      { value: 'cz75-auto', label: 'CZ75-Auto' },
      { value: 'r8', label: 'R8 Revolver' },
    ],
  },
  {
    id: 'smgs',
    placeholder: 'SMGs',
    selectedValue: '',
    options: [
      { value: 'smg', label: 'Todas las SMGs' },
      { value: 'mac-10', label: 'MAC-10' },
      { value: 'mp9', label: 'MP9' },
      { value: 'mp5-sd', label: 'MP5-SD' },
      { value: 'p90', label: 'P90' },
      { value: 'pp-bizon', label: 'PP-Bizon' },
      { value: 'ump-45', label: 'UMP-45' },
    ],
  },
  {
    id: 'heavy',
    placeholder: 'Armas Pesadas',
    selectedValue: '',
    options: [
      { value: 'heavy', label: 'Todas las Armas Pesadas' },
      { value: 'nova', label: 'Nova' },
      { value: 'xm1014', label: 'XM1014' },
      { value: 'mag-7', label: 'MAG-7' },
      { value: 'sawed-off', label: 'Sawed-Off' },
      { value: 'm249', label: 'M249' },
      { value: 'negev', label: 'Negev' },
    ],
  },
  {
    id: 'agents',
    placeholder: 'Agentes',
    selectedValue: '',
    options: [
      { value: 'agent', label: 'Todos los Agentes' },
      { value: 'ct', label: 'Agentes CT' },
      { value: 'tt', label: 'Agentes TT' },
    ],
  },
];
