# Generated by Django 5.2.3 on 2025-06-28 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0004_loan_review_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommended_by',
            field=models.ManyToManyField(related_name='recommendations', through='minilibrary.Recommendation', to=settings.AUTH_USER_MODEL),
        ),
    ]
