# Generated by Django 5.2.3 on 2025-06-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0005_book_recommended_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
